accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('intro/', views.intro, name='intro'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<username>/', views.mypage, name='mypage'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('nowplaying/', views.nowplaying, name='nowplaying'),
    path('upcoming/', views.upcoming, name='upcoming'),
    path('palette/', views.palette, name='palette'),
    path('palette/loading', views.loading, name='loading'),
    path('persona/', views.persona, name='persona'),
]

picka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

community/models.py
from django.db import models
from django.conf import settings


class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')


class Comment(models.Model):
    content = models.CharField(max_length=150)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['review', 'user']

community/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Review, Comment
from .forms import ReviewForm, CommentForm


@require_GET
def index(request):
    if request.user.is_authenticated:
        reviews = Review.objects.order_by('-pk')
        context = {
            'reviews': reviews,
        }
        return render(request, 'community/index.html', context)
    else:
        return redirect('accounts:intro')


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.user = request.user
                review.save()
                return redirect('community:detail', review.pk)
        else:
            form = ReviewForm()
        context = {
            'form': form,
        }
        return render(request, 'community/create.html', context)
    else:
        return redirect('accounts:intro')


@require_GET
def detail(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comments = review.comment_set.all()
        comment_form = CommentForm()
        context = {
            'review': review,
            'comment_form': comment_form,
            'comments': comments,
        }
        return render(request, 'community/detail.html', context)
    else:
        return redirect('accounts:intro')


@require_http_methods(['POST'])
def delete(request, review_pk):
    if request.user.is_authenticated:
        if request.method == 'POST':
            review = get_object_or_404(Review, pk=review_pk)        
            review.delete()
    return redirect('community:index')


@require_http_methods(['GET','POST'])
def update(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                review = form.save()
                return redirect('community:detail', review.pk)
        else:
            form = ReviewForm(instance=review)
        context = {
            'review': review,
            'form': form,
        }
        return render(request, 'community/update.html', context)
            

@require_POST
def create_comment(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
            return redirect('community:detail', review.pk)
        context = {
            'comment_form': comment_form,
            'review': review,
            'comments': review.comment_set.all(),
        }
        return render(request, 'community/detail.html', context)
    else:
        return redirect('accounts:intro')


@require_http_methods(['POST'])
def delete_comment(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        if request.method == 'POST':
            comment = get_object_or_404(Comment, pk=comment_pk)
            comment.delete()
        return redirect('community:detail', review_pk)


@require_POST
def like(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        user = request.user

        if review.like_users.filter(pk=user.pk).exists():
            review.like_users.remove(user)
            is_liked = False
        else:
            review.like_users.add(user)
            is_liked = True
        like_status = {'is_liked': is_liked, 'likes': review.like_users.count()}
        return JsonResponse(like_status)
    return redirect('accounts:login')

community/templates/community/create.html
{% extends 'base.html' %}


{% block title %}
<title>PICKA:게시글작성</title>
{% endblock title %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <a href="{% url 'movies:nowplaying' %}">
      <img src="/static/img/logo_picka.png" href="#page-top" style="width:200px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
        <li class="nav-item active" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:nowplaying' %}>NOW PLAYING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:upcoming' %}>UPCOMING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:loading' %}>PALETTE</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:persona' %}>PERSONA</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white" href={% url 'community:index' %}><b>COMMUNITY</b></a>
        </li>

      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <li class="nav-item" style="margin-right:20px;">
          <button class="nav-link btn btn-light opacity-75" style="padding-top:6px; padding-bottom:6px; padding-right:10px; padding-left:10px;">
            <a class="text-decoration-none text-black fw-bold" href={% url 'accounts:mypage' user.username %}>MYPAGE</a>
          </button>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-outline-light">
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/intro_image2.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;">
  <div class="d-flex justify-content-center">
    <div class="card bg-white bg-opacity-75" style="width: 70%; margin-top: 10%; margin-bottom: 10%">
      <div class="card-body d-flex-row opacity: 0;">
        <h1 class="card-title text-center fw-bold">Movie Community</h1>
        <hr>
        <div>
          <div class="mt-3">
            <section class="col-12">
              <div class="bg-success bg-opacity-75 rounded-2">
                  <h3 class="text-center py-2 fw-bold">리뷰 작성</h3>
              </div>
              <hr>
              <form class="fw-bold" action="{% url 'community:create' %}" method="POST">
                {% csrf_token %}
                <div class="container">
                  <!--리뷰제목-->
                  <div class="input-group mb-3 row d-flex align-items-center">
                    <div class="col-2">
                      <h5 class="fw-bold"> Review Title </h5>
                    </div>
                    <div class="col-5">
                      <input type="text" name="title" placeholder="리뷰 제목..." class="form-control">
                    </div>
                  </div>
      
                  <!--영화제목-->
                  <div class="input-group mb-3 row d-flex align-items-center">
                    <div class="col-2">
                      <h5 class="fw-bold"> Movie Title </h5>
                    </div>
                    <div class="col-5">
                      <input type="text" name="movie_title" placeholder="영화 제목..." class="form-control">            
                    </div>
                  </div>
          
                  <!--평점-->        
                  <div class="input-group mb-3 row d-flex align-items-center">
                    <div class="col-2">
                      <h5 class="fw-bold"> Rate </h5>
                    </div>
                    <div class="col-2">  
                      <input type="number" name="rank" placeholder="0.0" class="form-control" min=0 max=5 step=0.5>
                    </div>
                  </div>
          
                  <!--리뷰내용-->
                  <div class="input-group mb-2">
                    <div class="col-2">
                      <h5 class="fw-bold"> Review Content </h5>
                    </div>
                    <div class="col-10">
                      <input type="text" name="content" placeholder="리뷰 내용..." class="form-control" style="height: 200px">
                    </div>
                  </div>
                </div>
      
                <hr>
      
                <!--버튼-->
                <div class="d-flex mb-3 align-items-center justify-content-end">
                  <input type="submit" class="btn fw-bold btn-lg btn-success" value="게시하기">
                  <a class="btn btn-danger btn-lg mx-2 fw-bold" href={% url 'community:index' %}>게시글 작성 취소</a>
                </div>
              </form>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}


{% block style %}
<style>
  body, html {
    background-color: black;
    height: 100%;
    margin:0px;
  }
  
  .carousel,
  .carousel-item,
  .carousel-inner {
    height: 100%;
    width: 100%;
  }
</style>
{% endblock style %}

community/templates/community/detail.html
{% extends 'base.html' %}

{% block title %}
<title>PICKA:게시글상세</title>
{% endblock title %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <a href="{% url 'movies:nowplaying' %}">
      <img src="/static/img/logo_picka.png" href="#page-top" style="width:200px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
        <li class="nav-item active" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:nowplaying' %}>NOW PLAYING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:upcoming' %}>UPCOMING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:loading' %}>PALETTE</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:persona' %}>PERSONA</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white" href={% url 'community:index' %}><b>COMMUNITY</b></a>
        </li>

      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <li class="nav-item" style="margin-right:20px;">
          <button class="nav-link btn btn-light opacity-75" style="padding-top:6px; padding-bottom:6px; padding-right:10px; padding-left:10px;">
            <a class="text-decoration-none text-black fw-bold" href={% url 'accounts:mypage' user.username %}>MYPAGE</a>
          </button>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-outline-light">
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!--배경사진-->
<div style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/intro_image2.jpg');  background-repeat: round; ">

  <!--제목-->
  <div class="main d-flex justify-content-center">
    <div class="mt-5">
      {% comment %} <h1 class="fw-bold text-white mt-5">Movie Community</h1> {% endcomment %}
    </div>
  </div>

  <div class="container bg-white bg-opacity-75 border border-success rounded-4" style="margin-top:10%; margin-bottom:10%">
    <div class="mt-3">
      <section class="col-12">
        <div class="bg-success rounded-2">
            {% if review.pk == 1 %}
              <h3 class="text-center py-2 text-white">1st Review</h3>
            {% elif review.pk == 2 %}
              <h3 class="text-center py-2 text-white">2nd Review</h3>
            {% else %}
              <h3 class="text-center py-2 text-white">{{ review.pk }}th Review</h3>
            {% endif %}
        </div>
        <hr>

        <div>
          <!--작성내용-->
          <div class="container">
            <div class="row mb-3 d-flex align-items-center">
              <div class="col-2">
                <h5 class="fw-bold"> Review Title </h5>
              </div>
              <div class="col-10 border rounded bg-white bg-opacity-75"> 
                <h5> {{ review.title }} </h5> 
              </div>
            </div>

            <div class="row mb-3 d-flex align-items-center">
              <div class="col-2">
                <h5 class="fw-bold"> Movie Title </h5>
              </div>
              <div class="col-10 border rounded bg-white bg-opacity-75"> 
                <h5> {{ review.movie_title }} </h5> 
              </div>
            </div>

            <div class="row mb-3 d-flex align-items-center">
              <div class="col-2">
                <h5 class="fw-bold"> Rank </h5>
              </div>
              <div class="col-10 border rounded bg-white bg-opacity-75"> 
                <h5> {{ review.rank }} </h5> 
              </div>
            </div>

            <div class="row mb-2">
              <div class="col-2">
                <h5 class="fw-bold"> Review Content </h5>
              </div>
              <div class="col-10 border rounded bg-white bg-opacity-75" style="height: 200px"> 
                <h5> {{ review.content }} </h5> 
              </div>
            </div>

            <br>
            
            <!--추가정보-->
            <div class="row">
              <div class="col-5">
                {% if user != review.user %}
                <form class="d-inline" data-review-pk={{review.pk}}>
                  {% csrf_token %}
                  {% if user in review.like_users.all %}
                    <button class="btn mb-2 btn-danger" id="likeBtn">좋아요 취소</button>
                  {% else %}
                    <button class="btn mb-2 btn-success" id="likeBtn">좋아요</button>
                  {% endif %}
                </form>
                {% endif %}
                <p class="fw-bold" id="likeStatus">{{ review.like_users.all|length }} 명이 이 글을 좋아합니다.</p>
              </div>
              <div class="offset-2 col-5">
                <p class="fw-bold">|  작성자: {{ review.user }}</p>
                <p class="fw-bold">|  작성 시각: {{ review.created_at }}</p>
                <p class="fw-bold">|  수정 시각: {{ review.updated_at }}</p>
              </div>
            </div>
            
          </div>

          <!--댓글창-->
          <div class="container">
            <hr>
            {% if comments|length %}
              <h4 class="fw-bold">댓글 {{ comments|length }}개</h4>
            {% else %}
              <h4 class="fw-bold">댓글이 없습니다</h4>
            {% endif %}
            
            <div>
              <table class="table">
                <thead class="bg-success text-white">
                  <tr>
                    <th scope="col">Comment</th>
                    <th scope="col">Username</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col"></th>

                  </tr>
                </thead>
                <tbody class="bg-white bg-opacity-75">
                  {% for comment in comments %}
                    <tr>
                      <td>{{ comment.content }}</td>
                      <td>{{ comment.user }}</td>
                      <td>{{ comment.created_at }}</td>
                      <td>{{ comment.updated_at }}</td>
                      <td>
                        {% if request.user == comment.user %}
                          <form action="{% url 'community:delete_comment' review.pk comment.pk %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="댓글삭제">
                          </form>
                        {% endif %}
                      </td>
                    </tr>
                  {% empty %}
                    <p><b>댓글을 남겨주세요 </b></p>
                  {% endfor %}
                </tbody>
              </table>  
            </div>              
          </div>
          <hr>

          {% if request.user.is_authenticated %}
            <form action="{% url 'community:create_comment' review.pk %}" method="POST">
              <div class="d-flex-row">
                {% csrf_token %}
                <div class="container">
                  <div class="row">
                    <div class="col-11">
                      <input type="text" name="content" placeholder="댓글내용" class="form-control">
                    </div>
                    <div class="col-1">
                      <input class="btn btn-outline-success text-black fw-bold" type="submit" value="댓글달기">
                    </div>              
                  </div>                
              </div>
            </form>
          {% endif %}
          <hr>

          <div class="d-flex justify-content-end">
            {% if request.user == review.user %}
            <form action="{% url 'community:delete' review.pk %}" method="POST">
              {% csrf_token %}
              <input class="btn btn-danger btn-lg mx-2 mb-2 fw-bold" type="submit" value="게시글 삭제">
            </form>
              <a class="btn btn-warning btn-lg mx-2 mb-2 fw-bold" href="{% url 'community:update' review.pk %}">게시글 수정</a>
            {% endif %}
            <a class="btn btn-warning btn-lg mx-2 mb-2 fw-bold" href={% url 'community:index' %}>게시글 목록</a>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
{% endblock content %}


{% block script %}
<script>
  const likeForm = document.querySelector('.d-inline')
  const reviewPk = likeForm.dataset.reviewPk
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  const likeBtn = document.querySelector('#likeBtn')
  const likeStatus = document.querySelector('#likeStatus')

  likeForm.addEventListener('submit', onSubmit2)
  function onSubmit2(event) {
    event.preventDefault()

    axios({
      method: 'post',
      url: `http://127.0.0.1:8000/community/${reviewPk}/like/`,
      headers: {'X-CSRFToken': csrftoken},
    })
      .then(function (response) {
        console.log(response.data)
        const is_liked = response.data.is_liked
        const likes = response.data.likes

        if (is_liked) {
          likeBtn.innerText = '좋아요 취소'
        } else {
          likeBtn.innerText = '좋아요'
        }

        likeStatus.innerText = `${likes} 명이 이 글을 좋아합니다.`
      })
  }
  
</script>
{% endblock script %}


{% block style %}
<style>
  body, html {
    background-color: black;
    margin:0px;
  }

</style>
{% endblock style %}

community/templates/community/index.html
{% extends 'base.html' %}


{% block title %}
<title>PICKA:게시글목록</title>
{% endblock title %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <a href="{% url 'movies:nowplaying' %}">
      <img src="/static/img/logo_picka.png" href="#page-top" style="width:200px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
        <li class="nav-item active" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:nowplaying' %}>NOW PLAYING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:upcoming' %}>UPCOMING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:loading' %}>PALETTE</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:persona' %}>PERSONA</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white" href={% url 'community:index' %}><b>COMMUNITY</b></a>
        </li>

      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <li class="nav-item" style="margin-right:20px;">
          <button class="nav-link btn btn-light opacity-75" style="padding-top:6px; padding-bottom:6px; padding-right:10px; padding-left:10px;">
            <a class="text-decoration-none text-black fw-bold" href={% url 'accounts:mypage' user.username %}>MYPAGE</a>
          </button>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-outline-light">
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/intro_image2.jpg'); height: 100%;   background-position: center; background-repeat: no-repeat; background-size: cover;">
  <div class="d-flex justify-content-center">
    <div class="card bg-white bg-opacity-75" style="width: 70%; margin-top: 10%; margin-bottom: 10%;">
      <div class="card-body d-flex-row opacity: 0;">
        <h1 class="card-title text-center fw-bold">Movie Community</h1>
        <hr>
        <div>
          <div class="mt-3">
            <section class="col-12">
              <div class="d-none d-lg-block">
                <table class="table">
                  <thead class="bg-success text-white">
                    <tr>
                      <th scope="col">번호</th>
                      <th scope="col">영화 제목</th>
                      <th scope="col">글 제목</th>
                      <th scope="col">작성자</th>
                      <th scope="col">작성시간</th>
                      <th scope="col">마지막 수정시간</th>
                    </tr>
                  </thead>
                  <tbody class="bg-white bg-opacity-75">
                    {% for review in reviews %}
                      <tr>
                        <th scope="row">{{ review.pk }}</th>
                        <td class="fw-bold">{{ review.movie_title }}</td>
                        <td class="fw-bold"><a href="{% url 'community:detail' review.pk %}" class="text-decoration-none">{{ review.title }}</a></td>
                        <td class="fw-bold">{{ review.user }}</a></td>
                        <td class="fw-bold">{{ review.created_at }}</td>
                        <td class="fw-bold">{{ review.updated_at }}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>      
              </div>
            </section>
            <div class="d-flex justify-content-end">
              <a class="btn btn-warning btn-lg mb-2 me-2 fw-bold text-dark" href={% url 'community:create' %}>게시글 작성하기</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}


{% block style %}
<style>
  body, html {
    background-color: black;
    height: 100%;
    margin:0px;
  }
  
  .carousel,
  .carousel-item,
  .carousel-inner {
    height: 100%;
    width: 100%;
  }
</style>
{% endblock style %}