accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('intro/', views.intro, name='intro'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<username>/', views.mypage, name='mypage'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('nowplaying/', views.nowplaying, name='nowplaying'),
    path('upcoming/', views.upcoming, name='upcoming'),
    path('palette/', views.palette, name='palette'),
    path('palette/loading', views.loading, name='loading'),
    path('persona/', views.persona, name='persona'),
]

picka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
   pass

community/models.py
from django.db import models
from django.conf import settings


class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')


class Comment(models.Model):
    content = models.CharField(max_length=150)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms


class CustomUserChangeForm(UserChangeForm):

    # password = None

    class Meta:
        model = get_user_model()
        fields = (
            'email',
            'first_name',
            'last_name',
        )


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.TextInput(attrs={'placeholder': 'E-Mail'}),
        }

accounts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm


@require_http_methods(['GET', 'POST'])
def intro(request):
    if request.user.is_authenticated:
        return redirect('movies:nowplaying')
    return render(request, 'accounts/intro.html')


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:nowplaying')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:nowplaying')

    else:
        form = AuthenticationForm()
    context = {'form': form}

    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        return redirect('movies:nowplaying')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:nowplaying')

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:nowplaying')

    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/signup.html', context)


@login_required
def mypage(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    if request.user == person:
        context = {
            'person': person,
        }
        return render(request, 'accounts/mypage.html', context)
    else:
        return redirect('movies:nowplaying')


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:intro')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:intro')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('accounts:intro')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block title %}
<title>PICKA:비밀번호변경</title>
{% endblock title %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <a href="{% url 'movies:nowplaying' %}">
      <img src="/static/img/logo_picka.png" href="#page-top" style="width:200px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
        <li class="nav-item active" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:nowplaying' %}>NOW PLAYING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:upcoming' %}>UPCOMING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:loading' %}>PALETTE</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:persona' %}>PERSONA</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'community:index' %}><b>COMMUNITY</b></a>
        </li>

      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <li class="nav-item" style="margin-right:20px;">
          <button class="nav-link btn btn-light opacity-75" style="padding-top:6px; padding-bottom:6px; padding-right:10px; padding-left:10px;">
            <a class="text-decoration-none text-black fw-bold" href={% url 'accounts:mypage' user.username %}>MYPAGE</a>
          </button>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-outline-light">
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="bg" style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/intro_image4.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;">
  <div class="d-flex justify-content-center">
    <div class="card bg-white bg-opacity-75" style="width: 25%; margin-top: 10%">
      <div class="card-body d-flex-row opacity: 0;">
        <h4 class="card-title text-center fw-bold">비밀번호 변경</h4>
        <hr>
        
        <form action="{% url 'accounts:change_password' %}" method="POST">
          <div class="d-flex-row">
            {% csrf_token %}
            
             <div class="input-group mb-3">
              <input type="password" name="old_password" placeholder="이전 비밀번호" class="form-control">
            </div>
            <hr>
            <div class="input-group mb-2">
              <input type="password" name="new_password1" placeholder="새로운 비밀번호" class="form-control" >
            </div>
            <div class="input-group mb-2">
              <input type="password" name="new_password2" placeholder="새로운 비밀번호 확인" class="form-control" >
            </div> 
            <div class="fw-bold">
              <p>다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.</p>
              <p>비밀번호는 최소 8자 이상이어야 합니다.</p>
              <p>통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.</p>
              <p>숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</p>
            </div>
          </div>
          <hr>
          <div class="d-grid gap-2">
            <input type="submit" value="비밀번호 변경" class="btn btn-success">
          </div>
        </form>

        <br>

        <div class="d-flex justify-content-center">
          <a class="fw-bold text-decoration-none ms-3" href={% url 'accounts:mypage' user.username %}>MYPAGE로 돌아가기</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block style %}
<style>
  body, html {
    height: 100%;
    margin:0px;
  }
  
  .carousel,
  .carousel-item,
  .carousel-inner {
    height: 100%;
    width: 100%;
  }
</style>
{% endblock style %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block title %}
<title>PICKA:로그인</title>
{% endblock title %}

{% block content %}
<!-- Navigation-->
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <a href="{% url 'accounts:intro' %}">
      <img src="/static/img/logo_picka.png" href="#page-top" style="width:200px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <li class="nav-item">
          <a class="btn btn-outline-light" href={% url 'accounts:signup' %} role="button">회원가입</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<div class="bg" style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/loginpage_image.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;">
  <div class="d-flex justify-content-center">
    <div class="card;" style="width: 15%; margin-top: 15%">
      <div class="card-body d-flex-row opacity: 0;">
        <h4 class="card-title text-center fw-bold text-white">로그인</h4>
        <hr>
        
        <form action="{% url 'accounts:login' %}" method="POST">
          <div class="d-flex-row">
            {% csrf_token %}
            <div class="input-group mb-3">
              <input type="text" name="username" placeholder="Username..." class="form-control">
            </div>
            <div class="input-group mb-2">
              <input type="password" name="password" placeholder="Password..." class="form-control" >
            </div>
          </div>
          <hr>
          <div class="d-grid gap-2">
            <input type="submit" value="로그인" class="btn btn-success">
          </div>
        </form>
        <br>
        <div class="d-flex justify-content-center">
          <span class="text-white opacity-75">아직 아이디가 없으신가요?</span>
          <a class="text-white fw-bold text-decoration-none ms-3" href={% url 'accounts:signup' %}>회원가입</a>
        </div>
      </div>
    </div>
  </div>
</div>




<style>
  body, html {
  height: 100%;
  margin:0px;
  }
  
  
  
  </style>
{% endblock content %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}


{% block title %}
<title>PICKA:마이페이지</title>
{% endblock title %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <a href="{% url 'movies:nowplaying' %}">
      <img src="/static/img/logo_picka.png" href="#page-top" style="width:200px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
        <li class="nav-item active" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:nowplaying' %}>NOW PLAYING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:upcoming' %}>UPCOMING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:loading' %}>PALETTE</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:persona' %}>PERSONA</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'community:index' %}><b>COMMUNITY</b></a>
        </li>

      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <li class="nav-item" style="margin-right:20px;">
          <button class="nav-link btn btn-light opacity-75" style="padding-top:6px; padding-bottom:6px; padding-right:10px; padding-left:10px;">
            <a class="text-decoration-none text-black fw-bold" href={% url 'accounts:mypage' user.username %}>MYPAGE</a>
          </button>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-outline-light">
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>


<!--배경사진-->
<div class="bg" style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/mypage_image.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;">
  <div class="d-flex justify-content-center">
    <div class="card bg-white bg-opacity-75" style="width: 70%; margin-top: 5%">
      <div class="card-body d-flex-row opacity: 0;">
        <h2 class="card-title text-center fw-bold">{{ person.username }}님의 프로필</h2>
        <hr>
        <div>
          <div class="mt-3">
            <section class="container col-12">
              <div class="mt-3">
                <div>
                  <h4 class="text-center py-2 fw-bold">작성한 게시글 목록</h4>
                </div>
                <table class="table">
                  <thead class="bg-success text-white">
                    <tr>
                      <th scope="col">번호</th>
                      <th scope="col">영화 제목</th>
                      <th scope="col">글 제목</th>
                      <th scope="col">작성시간</th>
                      <th scope="col">마지막 수정시간</th>
                    </tr>
                  </thead>
                  <tbody class="bg-white bg-opacity-75">
                  {% for review in person.review_set.all %}
                    <tr>
                      <th scope="row">{{ review.pk }}</th>
                      <td>{{ review.movie_title }}</td>
                      <td><a href="{% url 'community:detail' review.pk %}">{{ review.title }}</a></td>
                      <td>{{ review.created_at }}</td>
                      <td>{{ review.updated_at }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
          
                <hr>
      
                <div>
                  <h4 class="text-center py-2 fw-bold">작성한 댓글 목록</h4>
                </div>
                <table class="table">
                  <thead class="bg-success text-white">
                    <tr>
                      <th scope="col">번호</th>
                      <th scope="col">글 제목</th>
                      <th scope="col">댓글 내용</th>
                    </tr>
                  </thead>
                  <tbody class="bg-white bg-opacity-75">
                    {% for comment in person.comment_set.all %}
                    <tr>
                      <th scope="row">{{ comment.pk }}</th>
                      <td><a href="{% url 'community:detail' comment.review.pk %}">{{ comment.review.title }}</a></td>
                      <td>{{ comment.content }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
                <hr>
              </div>
            
              <div>
                <div>
                  <h4 class="text-center py-2 fw-bold">계정관리</h4>
                </div>
                <div class="container">
                  <div class="row mb-2">
                    <a href={% url 'accounts:update' %} class="offset-2 col-8 btn btn-outline-warning fw-bold text-black">회원정보 수정</a>
                  </div>
                  <div class="row mb-2">
                    <a href={% url 'accounts:change_password' %} class="offset-2 col-8 btn btn-outline-warning fw-bold text-black">비밀번호 변경</a>
                  </div>      
                  <form action="{% url 'accounts:delete' %}" method="POST" id='delete_form' class="mb-3">
                    {% csrf_token %}
                    <div class="row">
                      <input type="submit" value="회원탈퇴" class="offset-2 col-8 btn btn-danger btn-lg btn-transparent me-4">
                    </div>
                  </form>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}

{% block style %}
<style>
  body, html {
    height: 100%;
    margin:0px;
  }
  
  .carousel,
  .carousel-item,
  .carousel-inner {
    height: 100%;
    width: 100%;
  }
</style>
{% endblock style %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}


{% block title %}
<title>PICKA:회원가입</title>
{% endblock title %}

{% block content %}
<!-- Navigation-->
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <img src="/static/img/logo_picka.png" href="{% url 'accounts:intro' %}" style="width:200px;">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <a class="btn btn-outline-light" href={% url 'accounts:login' %} role="button">로그인</a>
      </ul>
    </div>
  </div>
</nav>

<div class="bg" style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/signin_image.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;">
  <div class="d-flex justify-content-center">
    <div class="card;" style="width: 15%; margin-top: 15%">
      <div class="card-body d-flex-row opacity: 0;">
        <h4 class="card-title text-center fw-bold text-white">회원가입</h4>
        <hr>
  
        <form action="{% url 'accounts:signup' %}" method="POST">
          <div class="d-flex-row">
            {% csrf_token %}
            <div class="input-group mb-3">
              <input type="text" name="username" placeholder="Username..." class="form-control">
            </div>
            <hr>
            <div class="input-group mb-2">
              <input type="password" name="password1" placeholder="Password..." class="form-control" >
            </div>
            <div class="input-group mb-2">
              <input type="password" name="password2" placeholder="Password..." class="form-control" >
            </div>
          </div>
          <hr>
          <div class="d-grid gap-2">
            <input type="submit" value="회원가입" class="btn btn-success">
          </div>
        </form>
        <br>
        <div class="d-flex justify-content-center">
          <span class="text-white opacity-75">이미 아이디가 있으신가요?</span>
          <a class="text-white fw-bold text-decoration-none ms-3" href={% url 'accounts:login' %}>로그인</a>
        </div>
      </div>
    </div>
  </div>
</div>



<style>
  body, html {
  height: 100%;
  margin:0px;
  }
  
  
  
  </style>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}


{% block title %}
<title>PICKA:회원정보수정</title>
{% endblock title %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg" style="margin-top:10px;">
  <div class="container-fluid">
    <a href="{% url 'movies:nowplaying' %}">
      <img src="/static/img/logo_picka.png" href="#page-top" style="width:200px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20px;">
        <li class="nav-item active" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:nowplaying' %}>NOW PLAYING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:upcoming' %}>UPCOMING</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:loading' %}>PALETTE</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'movies:persona' %}>PERSONA</a>
        </li>
        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link text-white opacity-75" href={% url 'community:index' %}><b>COMMUNITY</b></a>
        </li>

      </ul>
      <ul class="navbar-nav" style="margin-right:20px;">
        <li class="nav-item" style="margin-right:20px;">
          <button class="nav-link btn btn-light opacity-75" style="padding-top:6px; padding-bottom:6px; padding-right:10px; padding-left:10px;">
            <a class="text-decoration-none text-black fw-bold" href={% url 'accounts:mypage' user.username %}>MYPAGE</a>
          </button>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃" class="btn btn-outline-light">
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="bg" style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url('/static/img/intro_image4.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;">
  <div class="d-flex justify-content-center">
    <div class="card bg-white bg-opacity-75" style="width: 25%; margin-top: 10%">
      <div class="card-body d-flex-row opacity: 0;">
        <h4 class="card-title text-center fw-bold">회원정보 수정</h4>
        <hr>
        
        <form action="{% url 'accounts:update' %}" method="POST">
          <div class="d-flex-row">
            {% csrf_token %}            
             <div class="input-group mb-2">
              <input type="text" name="email" placeholder="이메일 주소" class="form-control">
            </div>
            <div class="input-group mb-2">
              <input type="password" name="first_name" placeholder="이름 (first name)" class="form-control" >
            </div>
            <div class="input-group mb-2">
              <input type="password" name="last_name" placeholder="성 (last name)" class="form-control" >
            </div> 
            <div class="fw-bold">
              <p>비밀번호가 설정되지 않습니다.</p>
              <p>원본 비밀번호는 저장되지 않으므로, 해당 사용자의 비밀번호를 확인할 수 없습니다.</p>
              <p><a href="{% url 'accounts:change_password' %}"> 여기</a>를 눌러 비밀번호 변경하기</p>
            </div>
          </div>
          <hr>
          <div class="d-grid gap-2">
            <input type="submit" value="회원정보 수정" class="btn btn-success">
          </div>
        </form>

        <br>

        <div class="d-flex justify-content-center">
          <a class="fw-bold text-decoration-none ms-3" href={% url 'accounts:mypage' user.username %}>MYPAGE로 돌아가기</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block style %}
<style>
  body, html {
    height: 100%;
    margin:0px;
  }
  
  .carousel,
  .carousel-item,
  .carousel-inner {
    height: 100%;
    width: 100%;
  }
</style>
{% endblock style %}